import { useEffect, useState } from 'react'
import { ToastProvider, useToast } from './components/Toast'
import UniversalPrompt from './components/UniversalPrompt'
import { BrowserRouter, Routes, Route, Navigate, NavLink } from 'react-router-dom'
import AdminLogin from './pages/AdminLogin'
import ResetPassword from './pages/ResetPassword'
import AdminRegister from './pages/AdminRegister'
import Administrators from './pages/Administrators'
import AddPainting from './pages/AddPainting'
import Metadata from './pages/Metadata'
import PaintingList from './pages/PaintingList'
import EditPainting from './pages/EditPainting'
import Orders from './pages/Orders'
import OrderDetails from './pages/OrderDetails'
import Settings from './pages/Settings'
import { apiUrl } from './config/api'
import './App.css'
import './pages/Orders.css'
import './pages/OrderDetails.css'
import './pages/OrderStatusManager.css'
import './pages/OrderHeritageFixes.css'
import './AdminBrandFixes.css'
import './pages/Settings.css'
const menuItems=[{label:'Dashboard',icon:'⌂',path:'/'},{label:'Orders',icon:'◇',path:'/orders'},{label:'Paintings',icon:'▧',path:'/paintings'},{label:'Customers',icon:'♙',path:'/customers'},{label:'Payments',icon:'₹',path:'/payments'},{label:'Reports',icon:'▤',path:'/reports'},{label:'Metadata',icon:'◇',path:'/metadata'}]
const managementItems=[{label:'Administrators',icon:'♙',path:'/administrators'},{label:'Audit Log',icon:'◌',path:'/audit'},{label:'Settings',icon:'⚙',path:'/settings'}]
function AdminLogo({compact=false}){return <div className={`admin-logo${compact?' compact':''}`}><div className="admin-logo-mark">A</div><div className="admin-logo-copy"><div className="admin-logo-name">ARAmane Arts</div><div className="admin-logo-subtitle">ATELIER MANAGEMENT</div></div></div>}
function AdminLayout({children}){const[open,setOpen]=useState(false);const logout=async()=>{try{await fetch(apiUrl('admin/logout.php'),{method:'POST',credentials:'include'})}catch{}window.location.replace('/login')};return <div className="admin-app"><header className="admin-topbar"><div className="admin-brand"><button className="mobile-menu-button" onClick={()=>setOpen(true)}><span/><span/><span/></button><AdminLogo/></div><div className="admin-topbar-right"><span className="admin-role">ADMIN</span><div className="admin-profile"><div className="profile-avatar">A</div><div><strong>Administrator</strong><small>Administrator</small></div></div><button className="logout-button" onClick={logout}>Logout</button></div></header><div className="admin-body">{open&&<div className="sidebar-backdrop" onClick={()=>setOpen(false)}/>}<aside className={`admin-sidebar ${open?'mobile-open':''}`}><button className="mobile-sidebar-close" onClick={()=>setOpen(false)}>×</button><div className="admin-sidebar-logo"><AdminLogo compact/></div><div className="sidebar-heading">ATELIER MANAGEMENT</div><nav>{menuItems.map(i=><NavLink key={i.path} to={i.path} end={i.path==='/'} onClick={()=>setOpen(false)} className={({isActive})=>`admin-nav-link ${isActive?'active':''}`}><span className="nav-icon">{i.icon}</span><span>{i.label}</span></NavLink>)}</nav><div className="sidebar-divider"/><div className="sidebar-heading">ADMINISTRATION</div><nav>{managementItems.map(i=><NavLink key={i.path} to={i.path} onClick={()=>setOpen(false)} className={({isActive})=>`admin-nav-link ${isActive?'active':''}`}><span className="nav-icon">{i.icon}</span><span>{i.label}</span></NavLink>)}</nav><div className="sidebar-footer"><span>Built by Archith</span></div></aside><main className="admin-content">{children}</main></div></div>}
function MaintenanceControl(){const{toast}=useToast(),[enabled,setEnabled]=useState(false),[saving,setSaving]=useState(false),[prompt,setPrompt]=useState(false);useEffect(()=>{fetch(apiUrl('system/maintenance.php'),{credentials:'include',cache:'no-store'}).then(r=>r.json()).then(d=>d.success&&setEnabled(!!d.maintenance_mode)).catch(()=>{})},[]);const toggle=async()=>{const next=!enabled;setSaving(true);try{const r=await fetch(apiUrl('system/maintenance-toggle.php'),{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:next})}),d=await r.json().catch(()=>({}));if(!r.ok||!d.success)throw new Error(d.message);setEnabled(next);setPrompt(false);toast.success(d.message||'Maintenance mode updated.')}catch(e){toast.error(e.message||'Unable to change maintenance mode')}finally{setSaving(false)}};return <><button className={`maintenance-button${enabled?' active':''}`} onClick={()=>setPrompt(true)} disabled={saving}>{enabled?'● Maintenance On':'Maintenance Mode'}</button><UniversalPrompt open={prompt} eyebrow="MAINTENANCE MODE" title={enabled?'Turn off maintenance mode?':'Turn on maintenance mode?'} message={enabled?'This will reopen ARAmane Arts to customers.':'This will immediately close the customer website while you work.'} confirmLabel={enabled?'Turn Off Maintenance':'Turn On Maintenance'} cancelLabel="Keep As Is" onCancel={()=>setPrompt(false)} onConfirm={toggle} loading={saving} danger={!enabled}/></>}
function Dashboard(){const[stats,setStats]=useState({pending_orders:0,paintings:0,customers:0,revenue:0}),[loading,setLoading]=useState(true);const{toast}=useToast();useEffect(()=>{(async()=>{try{const r=await fetch(apiUrl('admin/dashboard.php'),{credentials:'include',cache:'no-store'}),d=await r.json().catch(()=>({}));if(!r.ok||!d.success)throw new Error(d.message);setStats(d)}catch(e){toast.error(e.message||'Unable to load dashboard')}finally{setLoading(false)}})()},[]);return <AdminLayout><div className="page-header"><div><span className="eyebrow">ATELIER OVERVIEW</span><h1>Dashboard</h1><p>Welcome back. Here is today's overview of ARAmane Arts.</p></div><MaintenanceControl/></div><div className="gold-rule"/><section className="dashboard-stats"><div className="heritage-card stat-card"><span className="stat-label">PENDING ORDERS</span><strong>{loading?'—':stats.pending_orders}</strong><span className="stat-note">Awaiting artist acceptance</span></div><div className="heritage-card stat-card"><span className="stat-label">PAINTINGS</span><strong>{loading?'—':stats.paintings}</strong><span className="stat-note">Currently in collection</span></div><div className="heritage-card stat-card"><span className="stat-label">CUSTOMERS</span><strong>{loading?'—':stats.customers}</strong><span className="stat-note">Registered customers</span></div><div className="heritage-card stat-card"><span className="stat-label">REVENUE</span><strong>{loading?'—':`₹${Number(stats.revenue||0).toLocaleString('en-IN')}`}</strong><span className="stat-note">Completed payments</span></div></section></AdminLayout>}
function PlaceholderPage({title}){return <AdminLayout><div className="page-header"><div><span className="eyebrow">ARAMANE ARTS</span><h1>{title}</h1><p>This section will be connected to the marketplace API next.</p></div></div><div className="gold-rule"/><div className="heritage-card placeholder-card"><div className="empty-state"><div className="empty-symbol">✦</div><h3>{title}</h3></div></div></AdminLayout>}
function ProtectedRoute({children}){const[state,setState]=useState('checking');useEffect(()=>{let mounted=true;fetch(apiUrl('auth/admin-session.php'),{credentials:'include'}).then(async r=>{const d=await r.json().catch(()=>({}));if(mounted)setState(r.ok&&d.success&&d.authenticated&&d.two_factor_verified?'authenticated':'unauthenticated')}).catch(()=>mounted&&setState('unauthenticated'));return()=>{mounted=false}},[]);if(state==='checking')return <div className="admin-app"><div style={{minHeight:'100vh',display:'grid',placeItems:'center'}}>Checking administrator access…</div></div>;return state==='authenticated'?children:<Navigate to="/login" replace/>}
const protectedPage=child=><ProtectedRoute><AdminLayout>{child}</AdminLayout></ProtectedRoute>
function App(){return <ToastProvider><BrowserRouter><Routes><Route path="/login" element={<AdminLogin/>}/><Route path="/reset-password" element={<ResetPassword/>}/><Route path="/register" element={<AdminRegister/>}/><Route path="/" element={<ProtectedRoute><Dashboard/></ProtectedRoute>}/><Route path="/orders" element={protectedPage(<Orders/>)}/><Route path="/orders/:id" element={protectedPage(<OrderDetails/>)}/><Route path="/paintings" element={protectedPage(<PaintingList/>)}/><Route path="/paintings/:id/edit" element={protectedPage(<EditPainting/>)}/><Route path="/paintings/new" element={protectedPage(<AddPainting/>)}/><Route path="/metadata" element={protectedPage(<Metadata/>)}/><Route path="/settings" element={protectedPage(<Settings/>)}/><Route path="/administrators" element={protectedPage(<Administrators/>)}/>{['/audit','/customers','/payments','/reports'].map(path=><Route key={path} path={path} element={<ProtectedRoute><PlaceholderPage title={managementItems.concat(menuItems).find(i=>i.path===path)?.label||'Management'}/></ProtectedRoute>}/>) }<Route path="*" element={<Navigate to="/" replace/>}/></Routes></BrowserRouter></ToastProvider>}
export default App
