import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useToast } from '../components/Toast'
import UniversalDropdown from '../components/UniversalDropdown'
import { apiUrl } from '../config/api'

export default function AddPainting(){
 const navigate=useNavigate(),{toast}=useToast();const[categories,setCategories]=useState([]),[frames,setFrames]=useState([]),[sizes,setSizes]=useState([]),[loading,setLoading]=useState(true),[images,setImages]=useState([]);const[form,setForm]=useState({name:'',category:'',description:'',price:'',width:'',height:'',frame:'',goldDetails:'',status:'available'}),[selectedSize,setSelectedSize]=useState('')
 useEffect(()=>{(async()=>{try{const[a,b,c]=await Promise.all([fetch(apiUrl('categories/list.php'),{credentials:'include'}),fetch(apiUrl('frames/list.php'),{credentials:'include'}),fetch(apiUrl('sizes/list.php'),{credentials:'include'})]);const[ca,fr,si]=await Promise.all([a.json(),b.json(),c.json()]);if(!ca.success)throw Error(ca.message||'Unable to load categories');if(!fr.success)throw Error(fr.message||'Unable to load frames');if(!si.success)throw Error(si.message||'Unable to load sizes');setCategories(ca.categories||[]);setFrames(fr.frames||[]);setSizes(si.sizes||[])}catch(e){toast.error(e.message||'Unable to load catalogue metadata')}finally{setLoading(false)}})()},[])
 const set=(n,v)=>setForm(p=>({...p,[n]:v}));const sizeChange=v=>{setSelectedSize(v);const s=sizes.find(x=>String(x.id)===String(v));if(s)setForm(p=>({...p,width:s.width,height:s.height}))};const upload=async id=>{if(!images.length)return;const fd=new FormData();fd.append('painting_id',id);images.forEach(f=>fd.append('images[]',f));const r=await fetch(apiUrl('paintings/upload-images.php'),{method:'POST',credentials:'include',body:fd}),d=await r.json().catch(()=>({}));if(!r.ok||!d.success)throw Error(d.message||'Unable to upload painting images')};const submit=async e=>{e.preventDefault();try{const r=await fetch(apiUrl('paintings/create.php'),{method:'POST',credentials:'include',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify(form)}),d=await r.json().catch(()=>({}));if(!r.ok||!d.success)throw Error(d.message||'Unable to create painting');const id=d.painting_id||d.id||d.painting?.id;if(!id)throw Error('Painting ID was not returned by the server');await upload(id);toast.success(images.length?'Painting and images saved successfully':'Painting created successfully');setTimeout(()=>navigate('/paintings'),700)}catch(e){console.error(e);toast.error(e.message||'Unable to save painting')}}
 const opts=(items)=>items.filter(x=>Number(x.is_active)===1).map(x=>({value:String(x.name),label:String(x.name)}));const sizeOpts=sizes.filter(x=>Number(x.is_active)===1).map(x=>({value:String(x.id),label:`${x.name} — ${x.width} × ${x.height} ${x.unit}`}));if(loading)return <div className="painting-form-page"><div className="heritage-card metadata-loading">Loading catalogue metadata...</div></div>
 return <div className="painting-form-page"><div className="page-header"><div><span className="eyebrow">ART COLLECTION</span><h1>Add Painting</h1><p>Add a new work to the ARAmane Arts collection.</p></div><button type="button" className="back-button" onClick={()=>navigate('/paintings')}>← Back to Paintings</button></div><div className="gold-rule"/><form className="painting-form" onSubmit={submit}>
 <section className="heritage-card form-section"><div className="form-section-heading"><span className="eyebrow">01 · ARTWORK</span><h2>Painting Details</h2><p>Basic information about the artwork.</p></div><div className="form-grid"><div className="form-field form-field-wide"><label>Painting Name</label><input value={form.name} onChange={e=>set('name',e.target.value)} required/></div><div className="form-field"><label>Category</label><UniversalDropdown value={form.category} onChange={v=>set('category',v)} options={opts(categories)} placeholder="Select category" required/></div><div className="form-field"><label>Status</label><UniversalDropdown value={form.status} onChange={v=>set('status',v)} options={[{value:'available',label:'Available'},{value:'unavailable',label:'Unavailable'}]}/></div><div className="form-field form-field-wide"><label>Description</label><textarea value={form.description} onChange={e=>set('description',e.target.value)} rows="5"/></div></div></section>
 <section className="heritage-card form-section"><div className="form-section-heading"><span className="eyebrow">02 · SPECIFICATIONS</span><h2>Artwork Specifications</h2><p>Dimensions, pricing and frame information.</p></div><div className="form-grid"><div className="form-field"><label>Price (₹)</label><input type="number" value={form.price} onChange={e=>set('price',e.target.value)} min="0" step="0.01" required/></div><div className="form-field"><label>Default Size</label><UniversalDropdown value={selectedSize} onChange={sizeChange} options={sizeOpts} placeholder="Select standard size"/></div><div className="form-field"><label>Width</label><input type="number" value={form.width} onChange={e=>set('width',e.target.value)} min="0" step="0.01" required/></div><div className="form-field"><label>Height</label><input type="number" value={form.height} onChange={e=>set('height',e.target.value)} min="0" step="0.01" required/></div><div className="form-field"><label>Frame</label><UniversalDropdown value={form.frame} onChange={v=>set('frame',v)} options={opts(frames)} placeholder="Select frame"/></div><div className="form-field form-field-wide"><label>Gold Details</label><input value={form.goldDetails} onChange={e=>set('goldDetails',e.target.value)} placeholder="22K gold foil, embossed details..."/></div></div></section>
 <section className="heritage-card form-section"><div className="form-section-heading"><span className="eyebrow">03 · IMAGES</span><h2>Painting Images</h2><p>Upload the artwork images for the catalogue.</p></div><div className="image-upload-area"><label className="upload-button">Choose Images<input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e=>{setImages(Array.from(e.target.files||[]));e.target.value=''}}/></label>{images.length>0&&<div className="image-carousel">{images.map((f,i)=><div className="image-carousel-card" key={`${f.name}-${i}`}><img src={URL.createObjectURL(f)} alt={`Selected artwork ${i+1}`}/><div className="image-carousel-info"><span>{i===0?'Primary image':`Image ${i+1}`}</span><small>{f.name}</small></div></div>)}</div>}</div></section>
 <div className="form-actions"><button type="button" className="cancel-button" onClick={()=>navigate('/paintings')}>Cancel</button><button type="submit" className="gold-outline-button">Save Painting</button></div></form></div>
}
