import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { apiUrl } from '../config/api'

export default function AdminLogin(){const navigate=useNavigate();const[step,setStep]=useState('credentials'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[otp,setOtp]=useState(''),[loading,setLoading]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');const clear=()=>{setMessage('');setError('')};
const login=async e=>{e.preventDefault();clear();setLoading(true);try{const r=await fetch(apiUrl('auth/login.php'),{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},credentials:'include',body:JSON.stringify({email:email.trim().toLowerCase(),password})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.success)throw new Error(d.message||'Unable to sign in.');if(d.requires_otp){setStep('otp');setMessage(d.message||'A verification code has been sent to your registered email.')}else if(d.authenticated)navigate('/',{replace:true});else throw new Error('Administrator authentication could not be completed.')}catch(e){setError(e.message||'Unable to sign in.')}finally{setLoading(false)}};
const verify=async e=>{e.preventDefault();clear();if(otp.length!==6){setError('Enter the 6-digit verification code.');return}setLoading(true);try{const r=await fetch(apiUrl('auth/verify-otp.php'),{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},credentials:'include',body:JSON.stringify({otp})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.success)throw new Error(d.message||'Invalid verification code.');navigate('/',{replace:true})}catch(e){setError(e.message||'Unable to verify the code.')}finally{setLoading(false)}};
const forgot=async e=>{e.preventDefault();clear();setLoading(true);try{const r=await fetch(apiUrl('admin/request-password-reset.php'),{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({email:email.trim().toLowerCase()})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.success)throw new Error(d.message||'Unable to send reset link.');setMessage(d.message)}catch(e){setError(e.message||'Unable to send reset link.')}finally{setLoading(false)}};
const title=step==='credentials'?'Welcome back':step==='otp'?'Verify your identity':'Forgot your password?';const desc=step==='credentials'?'Sign in to manage the ARAmane Arts collection.':step==='otp'?'Enter the verification code sent to your registered email address.':'Enter your administrator email and we will send you a secure reset link.';
return <main className="ara-login-page"><section className="ara-login-shell"><div className="ara-login-brand"><div className="ara-login-mark">A</div><div><div className="ara-login-brand-name">ARAmane Arts</div><div className="ara-login-brand-subtitle">Heritage Paintings</div></div></div><div className="ara-login-divider"><span/><b>✦</b><span/></div><div className="ara-login-heading"><p className="ara-login-eyebrow">ADMINISTRATION</p><h1>{title}</h1><p>{desc}</p></div>{step==='credentials'?<form className="ara-login-form" onSubmit={login}><label><span>Email address</span><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="admin@example.com" autoComplete="username" required/></label><label><span>Password</span><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter your password" autoComplete="current-password" required/></label><button className="ara-login-submit" disabled={loading}>{loading?'Signing in…':'Sign in'}{!loading&&<span>→</span>}</button><button className="ara-login-back" type="button" onClick={()=>{clear();setStep('forgot')}}>Forgot password?</button></form>:step==='otp'?<form className="ara-login-form" onSubmit={verify}><label><span>Verification code</span><input className="ara-otp-input" inputMode="numeric" pattern="[0-9]*" maxLength={6} value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,'').slice(0,6))} placeholder="000000" autoComplete="one-time-code" autoFocus required/></label><button className="ara-login-submit" disabled={loading}>{loading?'Verifying…':'Verify & continue'}</button><button className="ara-login-back" type="button" onClick={()=>{clear();setOtp('');setStep('credentials')}}>← Back to sign in</button></form>:<form className="ara-login-form" onSubmit={forgot}><label><span>Email address</span><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="admin@example.com" autoComplete="email" required/></label><button className="ara-login-submit" disabled={loading}>{loading?'Sending…':'Send reset link'}</button><button className="ara-login-back" type="button" onClick={()=>{clear();setStep('credentials')}}>← Back to sign in</button></form>}{message&&<div className="ara-login-message">{message}</div>}{error&&<div className="ara-login-error">{error}</div>}<div className="ara-login-footer"><span>ARAmane Arts</span><i>•</i><span>Private administration</span></div></section></main>}
