import { useEffect, useState } from 'react'
import { useNavigate,useParams } from 'react-router-dom'
import { useToast } from '../components/Toast'
import { apiUrl } from '../config/api'
import UniversalDropdown from '../components/UniversalDropdown'

export default function EditPainting(){
 const navigate=useNavigate(),{id}=useParams(),{toast}=useToast();const[categories,setCategories]=useState([]),[frames,setFrames]=useState([]),[sizes,setSizes]=useState([]),[images,setImages]=useState([]),[newImages,setNewImages]=useState([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[selectedSize,setSelectedSize]=useState('');const[form,setForm]=useState({name:'',category:'',description:'',price:'',width:'',height:'',frame:'',goldDetails:'',status:'available'})
 useEffect(()=>{(async()=>{try{const[r,c,f,s]=await Promise.all([fetch(apiUrl(`paintings/get.php?id=${encodeURIComponent(id)}`),{credentials:'include'}),fetch(apiUrl('categories/list.php'),{credentials:'include'}),fetch(apiUrl('frames/list.php'),{credentials:'include'}),fetch(apiUrl('sizes/list.php'),{credentials:'include'})]);const[p,ca,fr,si]=await Promise.all([r.json(),c.json(),f.json(),s.json()]);if(!p.success)throw Error(p.message||'Unable to load painting');if(!ca.success||!fr.success||!si.success)throw Error('Unable to load catalogue metadata');const x=p.painting;setCategories(ca.categories||[]);setFrames(fr.frames||[]);setSizes(si.sizes||[]);setImages(x.images||[]);setForm({name:x.name||'',category:x.category_name||'',description:x.description||'',price:x.price||'',width:x.width||'',height:x.height||'',frame:x.frame||'',goldDetails:x.gold_details||'',status:Number(x.is_active)===1?'available':'unavailable'});const standard=(x.size_options||[]).find(z=>Number(z.is_standard)===1);const match=(si.sizes||[]).find(z=>standard?(Number(z.width)===Number(standard.width)&&Number(z.height)===Number(standard.height)&&String(z.unit||'in')===String(standard.unit||'in')):(Number(z.width)===Number(x.width)&&Number(z.height)===Number(x.height)));setSelectedSize(match?String(match.id):'')}catch(e){toast.error(e.message||'Unable to load painting')}finally{setLoading(false)}})()},[id])
 const set=(n,v)=>setForm(p=>({...p,[n]:v}));const sizeChange=v=>{setSelectedSize(v);const s=sizes.find(x=>String(x.id)===String(v));if(s)setForm(p=>({...p,width:s.width,height:s.height}))};const upload=async()=>{if(!newImages.length)return;const fd=new FormData();fd.append('painting_id',id);newImages.forEach(f=>fd.append('images[]',f));const r=await fetch(apiUrl('paintings/upload-images.php'),{method:'POST',credentials:'include',body:fd}),d=await r.json().catch(()=>({}));if(!r.ok||!d.success)throw Error(d.message||'Unable to upload images');setImages(p=>[...p,...(d.images||[])]);setNewImages([])};const imageSrc=x=>{if(!x?.image_url)return '';if(/^https?:\/\//i.test(x.image_url))return x.image_url;return new URL(x.image_url.replace(/^\/+/,'/'),`${new URL(apiUrl('')).origin}/`).href};const save=async e=>{e.preventDefault();if(busy)return;setBusy(true);try{const r=await fetch(apiUrl('paintings/update.php'),{method:'PUT',credentials:'include',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({id,...form})}),d=await r.json().catch(()=>({}));if(!r.ok||!d.success)throw Error(d.message||'Unable to update painting');await upload();toast.success('Painting updated successfully');setTimeout(()=>navigate('/paintings'),700)}catch(e){toast.error(e.message||'Unable to update painting')}finally{setBusy(false)}}
 const opts=a=>a.filter(x=>Number(x.is_active)===1).map(x=>({value:String(x.name),label:String(x.name)}));const sizeOpts=sizes.filter(x=>Number(x.is_active)===1).map(x=>({value:String(x.id),label:`${x.name} — ${x.width} × ${x.height} ${x.unit}`}));if(loading)return <div className="painting-form-page"><div className="heritage-card metadata-loading">Loading painting...</div></div>
 return <div className="painting-form-page"><div className="page-header"><div><span className="eyebrow">ART COLLECTION</span><h1>Edit Painting</h1><p>Update the artwork details in the ARAmane Arts collection.</p></div><button type="button" className="back-button" onClick={()=>navigate('/paintings')}>← Back to Paintings</button></div><div className="gold-rule"/><form className="painting-form" onSubmit={save}>
 <section className="heritage-card form-section"><div className="form-section-heading"><span className="eyebrow">01 · ARTWORK</span><h2>Painting Details</h2></div><div className="form-grid"><div className="form-field form-field-wide"><label>Painting Name</label><input value={form.name} onChange={e=>set('name',e.target.value)} required/></div><div className="form-field"><label>Category</label><UniversalDropdown value={form.category} onChange={v=>set('category',v)} options={opts(categories)} placeholder="Select category" required/></div><div className="form-field"><label>Status</label><UniversalDropdown value={form.status} onChange={v=>set('status',v)} options={[{value:'available',label:'Available'},{value:'unavailable',label:'Unavailable'}]}/></div><div className="form-field form-field-wide"><label>Description</label><textarea value={form.description} onChange={e=>set('description',e.target.value)} rows="5"/></div></div></section>
 <section className="heritage-card form-section"><div className="form-section-heading"><span className="eyebrow">02 · SPECIFICATIONS</span><h2>Artwork Specifications</h2></div><div className="form-grid"><div className="form-field"><label>Price (₹)</label><input type="number" value={form.price} onChange={e=>set('price',e.target.value)} min="0" step="0.01" required/></div><div className="form-field"><label>Default Size</label><UniversalDropdown value={selectedSize} onChange={sizeChange} options={sizeOpts} placeholder="Custom size"/></div><div className="form-field"><label>Width</label><input type="number" value={form.width} onChange={e=>set('width',e.target.value)} min="0" step="0.01" required/></div><div className="form-field"><label>Height</label><input type="number" value={form.height} onChange={e=>set('height',e.target.value)} min="0" step="0.01" required/></div><div className="form-field"><label>Frame</label><UniversalDropdown value={form.frame} onChange={v=>set('frame',v)} options={opts(frames)} placeholder="Select frame"/></div><div className="form-field form-field-wide"><label>Gold Details</label><input value={form.goldDetails} onChange={e=>set('goldDetails',e.target.value)}/></div></div></section>
 <section className="heritage-card form-section"><div className="form-section-heading"><span className="eyebrow">03 · IMAGES</span><h2>Painting Images</h2></div><div className="image-upload-area"><label className="upload-button">Add Images<input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e=>{setNewImages(p=>[...p,...Array.from(e.target.files||[])]);e.target.value=''}}/></label>{(images.length||newImages.length)>0&&<div className="image-carousel">{images.map((im,i)=><div className="image-carousel-card" key={`existing-${im.id||i}`}><img src={imageSrc(im)} alt={`Artwork image ${i+1}`}/><div className="image-carousel-info"><span>{Number(im.is_primary)===1?'Primary image':`Image ${i+1}`}</span></div></div>)}{newImages.map((f,i)=><div className="image-carousel-card" key={`new-${f.name}-${i}`}><img src={URL.createObjectURL(f)} alt={`New artwork ${i+1}`}/><div className="image-carousel-info"><span>Pending upload</span><small>{f.name}</small></div></div>)}</div>}</div></section>
 <div className="form-actions"><button type="button" className="cancel-button" onClick={()=>navigate('/paintings')} disabled={busy}>Cancel</button><button type="submit" className="gold-outline-button" disabled={busy}>{busy?'Saving...':'Update Painting'}</button></div></form></div>
}
