import { useState } from 'react'
import { useToast } from '../components/Toast'
import UniversalDropdown from '../components/UniversalDropdown'
import UniversalPrompt from '../components/UniversalPrompt'

const STATUSES=[['PENDING_ACCEPTANCE','Pending Acceptance'],['ACCEPTED','Accepted'],['PAYMENT_DUE','Payment Due'],['PAID','Paid'],['PROCESSING','Processing'],['DISPATCHED','Dispatched'],['DELIVERED','Delivered'],['REJECTED','Rejected']]
const API='http://localhost/paintings/api'; const money=value=>Number(value||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})

export default function OrderStatusManager({order,onUpdated}){
 const {toast}=useToast();const [status,setStatus]=useState(order?.status||'PENDING_ACCEPTANCE');const [notes,setNotes]=useState('');const [saving,setSaving]=useState(false);const [pricing,setPricing]=useState({base_amount:order?.base_amount??order?.subtotal??'',customization_amount:order?.customization_amount??'0',delivery_amount:order?.delivery_amount??order?.shipping_amount??'0',discount_amount:order?.discount_amount??'0',payment_link:order?.payment_link??''});const [releasing,setReleasing]=useState(false);const [prompt,setPrompt]=useState(null)
 if(!order)return null;const cancelled=order.status==='CANCELLED'
 const saveStatus=async()=>{if(saving||cancelled)return;setPrompt(null);setSaving(true);try{const response=await fetch(`${API}/orders/update-status.php`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({order_id:order.id,action:status,notes:notes.trim()})});const data=await response.json().catch(()=>({}));if(!response.ok||!data.success)throw new Error(data.message||'Unable to update order status');setNotes('');onUpdated?.();toast.success('Order status updated')}catch(error){toast.error(error.message||'Unable to update order status')}finally{setSaving(false)}}
 const releasePrice=async()=>{if(releasing||cancelled)return;setPrompt(null);const payload={order_id:order.id,...Object.fromEntries(Object.entries(pricing).map(([key,value])=>[key,key==='payment_link'?value:Number(value||0)])),notes:notes.trim()};setReleasing(true);try{const response=await fetch(`${API}/orders/release-price.php`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify(payload)});const data=await response.json().catch(()=>({}));if(!response.ok||!data.success)throw new Error(data.message||'Unable to release final price');setNotes('');onUpdated?.();toast.success('Final price released. The customer can now view the quotation.')}catch(error){toast.error(error.message||'Unable to release final price')}finally{setReleasing(false)}}
 const canRelease=!cancelled&&(order.status==='ACCEPTED'||order.status==='PAYMENT_DUE');const finalAmount=Number(pricing.base_amount||0)+Number(pricing.customization_amount||0)+Number(pricing.delivery_amount||0)-Number(pricing.discount_amount||0);const statusChanged=status!==order.status||Boolean(notes.trim())
 return <><UniversalPrompt open={Boolean(prompt)} eyebrow={prompt?.type==='price'?'RELEASE QUOTATION':'UPDATE ORDER'} title={prompt?.type==='price'?'Release this quotation?':'Update this order status?'} message={prompt?.type==='price'?`The customer will be able to see the final amount of ₹${money(finalAmount)}${pricing.payment_link?' and use the supplied payment link':''}.`:<>Change status to <strong>{STATUSES.find(([value])=>value===status)?.[1]||status}</strong>{notes.trim()?' and add the entered note':''}.</>} confirmLabel={prompt?.type==='price'?'Release Price':'Save Status'} cancelLabel="Go Back" onConfirm={prompt?.type==='price'?releasePrice:saveStatus} onCancel={()=>setPrompt(null)} loading={saving||releasing}/>{prompt?.type==='price'&&<span aria-hidden="true"/>}
 <section className="heritage-card order-status-manager"><div className="order-status-manager-copy"><span className="eyebrow">ORDER CONTROL</span><h2>{cancelled?'Order Cancelled':'Update Order Status'}</h2><p>{cancelled?'This order was cancelled by the customer and can no longer be edited.':'Change the customer-facing status. The tracking page refreshes automatically.'}</p></div>{!cancelled&&<div className="order-status-manager-controls"><label><span>STATUS</span><UniversalDropdown value={status} onChange={setStatus} options={STATUSES.map(([value,label])=>({value,label}))} disabled={saving}/></label><label><span>NOTE <small>(optional)</small></span><input value={notes} onChange={event=>setNotes(event.target.value)} maxLength={2000} placeholder="Add an internal status note" disabled={saving}/></label><button type="button" className="order-status-save" onClick={()=>setPrompt({type:'status'})} disabled={saving||!statusChanged}>Save Status</button></div>}</section>{canRelease&&<section className="heritage-card order-price-release-card"><div className="form-section-heading"><span className="eyebrow">FINAL QUOTATION</span><h2>Release Price to Customer</h2><p>The customer will see this breakdown after you release it. The payment link is optional and can be added manually.</p></div><div className="order-price-grid"><label><span>BASE PRICE</span><input type="number" min="0" step="0.01" value={pricing.base_amount} onChange={e=>setPricing({...pricing,base_amount:e.target.value})}/></label><label><span>CUSTOMIZATION FEE</span><input type="number" min="0" step="0.01" value={pricing.customization_amount} onChange={e=>setPricing({...pricing,customization_amount:e.target.value})}/></label><label><span>DELIVERY FEE</span><input type="number" min="0" step="0.01" value={pricing.delivery_amount} onChange={e=>setPricing({...pricing,delivery_amount:e.target.value})}/></label><label><span>DISCOUNT</span><input type="number" min="0" step="0.01" value={pricing.discount_amount} onChange={e=>setPricing({...pricing,discount_amount:e.target.value})}/></label><label className="order-price-link-field"><span>PAYMENT LINK <small>(optional)</small></span><input type="url" value={pricing.payment_link} onChange={e=>setPricing({...pricing,payment_link:e.target.value})} placeholder="https://…"/></label></div><div className="order-price-release-total"><span>FINAL AMOUNT</span><strong>₹{money(finalAmount)}</strong></div><button type="button" className="order-price-release-button" onClick={()=>setPrompt({type:'price'})} disabled={releasing||finalAmount<0}>{releasing?'Releasing…':order.status==='PAYMENT_DUE'?'Update Released Price':'Release Price & Request Payment'}</button></section>}</>
}
