import { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { useToast } from '../components/Toast'

const API='http://localhost/paintings/api'
const statusLabels={PENDING_ACCEPTANCE:'Pending Acceptance',ACCEPTED:'Accepted',PAYMENT_DUE:'Payment Due',PAID:'Paid',PROCESSING:'Processing',DISPATCHED:'Dispatched',DELIVERED:'Delivered',REJECTED:'Rejected',CANCELLED:'Cancelled'}
const statusClasses={PENDING_ACCEPTANCE:'pending',ACCEPTED:'accepted',PAYMENT_DUE:'payment-due',PAID:'paid',PROCESSING:'processing',DISPATCHED:'dispatched',DELIVERED:'delivered',REJECTED:'rejected',CANCELLED:'cancelled'}
const formatDate=value=>value?new Date(String(value).replace(' ','T')).toLocaleString('en-IN',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}):'—'
const formatAmount=value=>Number(value||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})

export default function OrderDetails(){
 const navigate=useNavigate();const {id}=useParams();const {toast}=useToast();const [order,setOrder]=useState(null);const [loading,setLoading]=useState(true);const [actionPrompt,setActionPrompt]=useState(null);const [actionNotes,setActionNotes]=useState('');const [actionLoading,setActionLoading]=useState(false);const [history,setHistory]=useState([])
 useEffect(()=>{loadOrder()},[id])
 const loadOrder=async()=>{setLoading(true);try{const r=await fetch(`${API}/orders/get.php?id=${id}`,{credentials:'include',cache:'no-store'});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.message||'Unable to load order');setOrder(d.order);const hr=await fetch(`${API}/orders/history.php?order_id=${id}`,{credentials:'include'});const hd=await hr.json();if(hr.ok&&hd.success)setHistory(hd.history||[])}catch(e){toast.error(e.message||'Unable to load order')}finally{setLoading(false)}}
 const handleOrderAction=async()=>{if(!actionPrompt||actionLoading)return;setActionLoading(true);try{const r=await fetch(`${API}/orders/update-status.php`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({order_id:order.id,action:actionPrompt,notes:actionNotes.trim()})});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.message||'Unable to update order');await loadOrder();toast.success(d.message);setActionPrompt(null);setActionNotes('')}catch(e){toast.error(e.message||'Unable to update order')}finally{setActionLoading(false)}}
 if(loading)return <div className="order-details-page"><div className="heritage-card metadata-loading">Loading order...</div></div>
 if(!order)return <div className="order-details-page"><div className="page-header"><div><span className="eyebrow">ORDER MANAGEMENT</span><h1>Order Not Found</h1></div><button className="back-button" onClick={()=>navigate('/orders')}>← Back to Orders</button></div></div>
 return <div className="order-details-page">
  <div className="page-header"><div><span className="eyebrow">ORDER MANAGEMENT</span><h1>Order #{order.order_number}</h1><p>Placed on {formatDate(order.created_at)}</p></div><button className="back-button" onClick={()=>navigate('/orders')}>← Back to Orders</button></div><div className="gold-rule"/>
  <section className="heritage-card order-summary-card"><div><span className="eyebrow">CURRENT STATUS</span><div className="order-detail-status-row"><span className={`order-status-badge ${statusClasses[order.status]||''}`}>{statusLabels[order.status]||order.status}</span></div></div><div className="order-summary-total"><span>{order.price_released_at?'FINAL TOTAL':'BASE PRICE'}</span><strong>₹{formatAmount(order.total_amount)}</strong></div>{order.status==='PENDING_ACCEPTANCE'&&<div className="order-action-buttons"><button className="order-reject-button" onClick={()=>{setActionPrompt('REJECT');setActionNotes('')}}>Reject Order</button><button className="order-accept-button" onClick={()=>{setActionPrompt('ACCEPTED');setActionNotes('')}}>Accept Order</button></div>}</section>
  <div className="order-detail-grid"><section className="heritage-card"><div className="form-section-heading"><span className="eyebrow">01 · CUSTOMER</span><h2>Customer Information</h2></div><div className="order-info-list"><div><span>NAME</span><strong>{order.shipping_name||'—'}</strong></div><div><span>PHONE</span><strong>{order.shipping_phone||'—'}</strong></div><div><span>CUSTOMER ID</span><strong>{order.user_id||'—'}</strong></div></div></section><section className="heritage-card"><div className="form-section-heading"><span className="eyebrow">02 · DELIVERY</span><h2>Shipping Address</h2></div><div className="order-address"><strong>{order.shipping_name||'—'}</strong><span>{order.shipping_address_line_1||''}</span>{order.shipping_address_line_2&&<span>{order.shipping_address_line_2}</span>}<span>{order.shipping_city||''}{order.shipping_state?`, ${order.shipping_state}`:''}</span><span>{order.shipping_postal_code||''}</span><span>{order.shipping_country||''}</span></div></section></div>
  <section className="heritage-card order-items-card"><div className="form-section-heading"><span className="eyebrow">03 · ARTWORK</span><h2>Ordered Paintings</h2><p>{order.items?.length||0} item{order.items?.length===1?'':'s'} in this order.</p></div><div className="order-items">{(order.items||[]).map(item=><div className="order-item" key={item.id}><div className="order-item-art"><div className="order-item-symbol">✦</div><div><strong>{item.painting_name}</strong><span>{item.artist_name||'ARAmane Arts'}</span></div></div><div className="order-item-quantity"><span>QTY</span><strong>{item.quantity}</strong></div><div className="order-item-price"><span>₹{formatAmount(item.unit_price)}</span><strong>₹{formatAmount(item.total_price)}</strong></div></div>)}</div></section>
  <section className="heritage-card order-financial-card"><div className="form-section-heading"><span className="eyebrow">04 · ORDER VALUE</span><h2>{order.price_released_at?'Released Quotation':'Base Order Value'}</h2></div><div className="order-financial-list"><div><span>Base price</span><strong>₹{formatAmount(order.base_amount??order.subtotal)}</strong></div>{order.price_released_at&&<><div><span>Customization fee</span><strong>₹{formatAmount(order.customization_amount)}</strong></div><div><span>Delivery fee</span><strong>₹{formatAmount(order.delivery_amount??order.shipping_amount)}</strong></div><div><span>Discount</span><strong>− ₹{formatAmount(order.discount_amount)}</strong></div></>}<div className="order-financial-total"><span>Final total</span><strong>₹{formatAmount(order.total_amount)}</strong></div></div>{order.price_released_at&&<div style={{marginTop:'1rem',fontSize:'.9rem'}}>Payment link: {order.payment_link?<a className="order-tracking-link" href={order.payment_link} target="_blank" rel="noreferrer">Open payment link →</a>:'Not added yet'}</div>}</section>
  {(order.customer_notes||order.artist_notes)&&<section className="order-detail-grid">{order.customer_notes&&<div className="heritage-card"><div className="form-section-heading"><span className="eyebrow">05 · CUSTOMER NOTE</span><h2>Customer Requirements</h2></div><p className="order-note">{order.customer_notes}</p></div>}{order.artist_notes&&<div className="heritage-card"><div className="form-section-heading"><span className="eyebrow">06 · ARTIST NOTE</span><h2>Artist Notes</h2></div><p className="order-note">{order.artist_notes}</p></div>}</section>}
  {(order.tracking_courier||order.tracking_id||order.tracking_url)&&<section className="heritage-card"><div className="form-section-heading"><span className="eyebrow">DELIVERY</span><h2>Tracking Information</h2></div><div className="order-info-list"><div><span>COURIER</span><strong>{order.tracking_courier||'—'}</strong></div><div><span>TRACKING ID</span><strong>{order.tracking_id||'—'}</strong></div>{order.tracking_url&&<div><span>TRACKING</span><a href={order.tracking_url} target="_blank" rel="noreferrer" className="order-tracking-link">Open Tracking →</a></div>}</div></section>}
  <section className="heritage-card"><div className="form-section-heading"><span className="eyebrow">ORDER TIMELINE</span><h2>Important Dates</h2></div><div className="order-timeline-grid"><div><span>ORDERED</span><strong>{formatDate(order.created_at)}</strong></div><div><span>ACCEPTED</span><strong>{formatDate(order.accepted_at)}</strong></div><div><span>PRICE RELEASED</span><strong>{formatDate(order.price_released_at)}</strong></div><div><span>PAID</span><strong>{formatDate(order.paid_at)}</strong></div><div><span>DISPATCHED</span><strong>{formatDate(order.dispatched_at)}</strong></div><div><span>DELIVERED</span><strong>{formatDate(order.delivered_at)}</strong></div></div></section>
  <section className="heritage-card order-history-card"><div className="form-section-heading"><span className="eyebrow">STATUS HISTORY</span><h2>Order Journey</h2><p>A record of every status change for this order.</p></div>{history.length===0?<p className="order-note">No status history available.</p>:<div className="order-history-list">{history.map(entry=><div className="order-history-item" key={entry.id}><div><strong>{statusLabels[entry.new_status]||entry.new_status}</strong><span>{formatDate(entry.created_at)}</span></div><p>{entry.notes||'Status updated.'}</p></div>)}</div>}</section>
  {actionPrompt&&<div className="order-action-overlay"><div className="order-action-modal"><span className="eyebrow">CONFIRM ACTION</span><h2>{actionPrompt==='REJECT'?'Reject Order':'Accept Order'}</h2><p>{actionPrompt==='REJECT'?'This will reject the customer order.':'This will accept the order and allow you to release the final quotation.'}</p><textarea value={actionNotes} onChange={e=>setActionNotes(e.target.value)} maxLength={2000} placeholder="Add a note (optional)"/><div><button className="order-modal-cancel" onClick={()=>setActionPrompt(null)}>Cancel</button><button className="order-modal-confirm" onClick={handleOrderAction} disabled={actionLoading}>{actionLoading?'Saving…':'Confirm'}</button></div></div></div>}
 </div>
}
