import { useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { apiUrl } from '../config/api'

export default function ResetPassword(){
 const[params]=useSearchParams(),token=params.get('token')||'';const[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[loading,setLoading]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')
 const submit=async e=>{e.preventDefault();setMessage('');setError('');if(!token){setError('This password reset link is invalid.');return}if(password.length<8){setError('Password must be at least 8 characters.');return}if(password!==confirm){setError('The passwords do not match.');return}setLoading(true);try{const r=await fetch(apiUrl('auth/reset-password.php'),{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({token,password})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.success)throw new Error(d.message||'Unable to reset password.');setMessage(d.message||'Password reset successfully.');setPassword('');setConfirm('')}catch(e){setError(e.message||'Unable to reset password.')}finally{setLoading(false)}}
 return <main className="ara-login-page"><section className="ara-login-shell"><div className="ara-login-brand"><div className="ara-login-mark">A</div><div><div className="ara-login-brand-name">ARAmane Arts</div><div className="ara-login-brand-subtitle">Heritage Paintings</div></div></div><div className="ara-login-divider"><span/><b>✦</b><span/></div><div className="ara-login-heading"><p className="ara-login-eyebrow">ADMINISTRATION · SECURITY</p><h1>Choose a new password</h1><p>Set a new password for your administrator account.</p></div>{!message&&<form className="ara-login-form" onSubmit={submit}><label><span>New password</span><input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={8} autoComplete="new-password" required/></label><label><span>Confirm new password</span><input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} minLength={8} autoComplete="new-password" required/></label><button className="ara-login-submit" disabled={loading}>{loading?'Resetting…':'Reset password'}</button></form>}{message&&<div className="ara-login-message">{message}</div>}{error&&<div className="ara-login-error">{error}</div>}<div className="ara-login-switch"><Link to="/login">← Back to administrator sign in</Link></div></section></main>
}
