import { useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { apiUrl } from '../config/api'
import { useToast } from '../components/ToastProvider'
import UniversalDropdown from '../components/UniversalDropdown'
import UniversalPrompt from '../components/UniversalPrompt'

export default function Cart(){
 const navigate=useNavigate();const {toast}=useToast();const [items,setItems]=useState([]);const [loading,setLoading]=useState(true);const [formData,setFormData]=useState({shipping_name:'',shipping_phone:'',shipping_email:'',shipping_address:'',shipping_city:'',shipping_state:'',shipping_postal_code:'',shipping_country:''});const [checkoutLoading,setCheckoutLoading]=useState(false);const [updatingId,setUpdatingId]=useState(0);const [removeTarget,setRemoveTarget]=useState(null)
 const loadCart=async()=>{try{setLoading(true);const r=await fetch(apiUrl('cart/get.php'),{credentials:'include'});const d=await r.json().catch(()=>({}));if(r.status===401){navigate('/login');return}if(!r.ok||!d.success)throw new Error(d.message||'Unable to load your order.');setItems(d.items||[])}catch(e){toast.error(e.message||'Unable to load your order.')}finally{setLoading(false)}}
 useEffect(()=>{loadCart()},[])
 const getImageUrl=url=>!url?'':url.startsWith('http')?url:`http://localhost${url}`
 const getOptions=item=>Array.isArray(item.size_options)?item.size_options:[]
 const selectedOption=item=>getOptions(item).find(o=>Number(o.id)===Number(item.size_option_id))||getOptions(item).find(o=>Number(o.is_standard)===1)||getOptions(item)[0]
 const price=item=>Number(selectedOption(item)?.price||item.discount_price||item.price||0)
 const subtotal=items.reduce((sum,item)=>sum+price(item),0)
 const change=e=>setFormData({...formData,[e.target.name]:e.target.value})
 const updateItem=async(item,changes={})=>{setUpdatingId(item.cart_item_id);try{const r=await fetch(apiUrl('cart/update-item.php'),{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({cart_item_id:item.cart_item_id,quantity:1,...changes})});const d=await r.json().catch(()=>({}));if(r.status===401){navigate('/login');return}if(!r.ok||!d.success)throw new Error(d.message||'Unable to update your order.');await loadCart();window.dispatchEvent(new Event('ara-cart-updated'));toast.success('Order updated')}catch(e){toast.error(e.message||'Unable to update your order.')}finally{setUpdatingId(0)}}
 const removeItem=async item=>{setRemoveTarget(null);setUpdatingId(item.cart_item_id);try{const r=await fetch(apiUrl('cart/remove-item.php'),{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({cart_item_id:item.cart_item_id})});const d=await r.json().catch(()=>({}));if(r.status===401){navigate('/login');return}if(!r.ok||!d.success)throw new Error(d.message||'Unable to remove the item.');await loadCart();window.dispatchEvent(new Event('ara-cart-updated'));toast.success('Artwork removed from your order')}catch(e){toast.error(e.message||'Unable to remove the item.')}finally{setUpdatingId(0)}}
 const checkout=async e=>{e.preventDefault();setCheckoutLoading(true);try{const r=await fetch(apiUrl('orders/create.php'),{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify(formData)});const d=await r.json().catch(()=>({}));if(r.status===401){navigate('/login');return}if(!r.ok||!d.success)throw new Error(d.message||'Order submission failed.');window.dispatchEvent(new Event('ara-cart-updated'));toast.success('Order request submitted successfully.');navigate('/track-orders')}catch(e){toast.error(e.message||'Order submission failed.')}finally{setCheckoutLoading(false)}}
 if(loading)return <div className="ara-collection-state"><span className="ara-loader"></span><p>Loading your order...</p></div>
 return <main className="ara-cart-page">
  <UniversalPrompt open={Boolean(removeTarget)} eyebrow="REMOVE ARTWORK" title="Remove this artwork?" message={removeTarget?`Remove “${removeTarget.name}” from your order?`:''} confirmLabel="Remove Artwork" cancelLabel="Keep Artwork" onConfirm={()=>removeItem(removeTarget)} onCancel={()=>setRemoveTarget(null)} loading={updatingId===removeTarget?.cart_item_id} danger/>
  <header className="ara-cart-header"><div className="ara-cart-kicker"><span></span>YOUR ORDER<span></span></div><h1>Complete Your Order</h1><p>Select a size for each artwork and tell us where to reach you.</p></header>
  {!items.length?<div className="ara-cart-empty"><h2>Your order is empty</h2><p>Explore our collection and add a painting to begin your order.</p><Link to="/paintings" className="ara-btn ara-btn-primary">Explore Paintings</Link></div>:<>
   <section className="ara-cart-items" aria-label="Paintings in your order">{items.map(item=>{const options=getOptions(item);const option=selectedOption(item);return <article className="ara-cart-item" key={item.cart_item_id}>
    <div className="ara-cart-item-image">{item.image_url&&<img src={getImageUrl(item.image_url)} alt={item.name}/>}</div>
    <div><p className="ara-cart-item-category">{item.category_name||'Heritage Art'}</p><h2>{item.name}</h2><div className="ara-cart-item-size"><label htmlFor={`size-${item.cart_item_id}`}>Size</label><UniversalDropdown id={`size-${item.cart_item_id}`} value={option?.id||''} disabled={!options.length||updatingId===item.cart_item_id} options={options.map(o=>({value:o.id,label:`${o.name||`${o.width} × ${o.height} ${o.unit||'in'}`} · ${formatPrice(o.price)}`}))} onChange={value=>updateItem(item,{size_option_id:Number(value)})} /></div><p className="ara-cart-item-meta">{option?`${option.width} × ${option.height} ${option.unit||'in'}`:'Standard size'} · One artwork</p><button type="button" className="ara-remove" onClick={()=>setRemoveTarget(item)} disabled={updatingId===item.cart_item_id}>Remove</button></div><div className="ara-cart-item-price">{formatPrice(price(item))}</div>
   </article>})}</section>
   <section className="ara-order-form-wrap"><div className="ara-form-intro"><div><span className="ara-form-eyebrow">ORDER DETAILS</span><h2 className="ara-form-heading">Where should we reach you?</h2></div><div className="ara-form-total"><span>Artwork total</span><strong>{formatPrice(subtotal)}</strong></div></div><form className="ara-order-form" onSubmit={checkout}>
    <div className="ara-form-grid"><div><label htmlFor="shipping_name">Full name</label><input id="shipping_name" type="text" name="shipping_name" value={formData.shipping_name} onChange={change} autoComplete="name" required/></div><div><label htmlFor="shipping_phone">Phone number</label><input id="shipping_phone" type="tel" name="shipping_phone" value={formData.shipping_phone} onChange={change} autoComplete="tel" required/></div><div><label htmlFor="shipping_email">Email address</label><input id="shipping_email" type="email" name="shipping_email" value={formData.shipping_email} onChange={change} autoComplete="email" required/></div><div className="ara-form-address"><label htmlFor="shipping_address">Address</label><textarea id="shipping_address" name="shipping_address" value={formData.shipping_address} onChange={change} autoComplete="street-address" required/></div><div><label htmlFor="shipping_city">City</label><input id="shipping_city" type="text" name="shipping_city" value={formData.shipping_city} onChange={change} autoComplete="address-level2" required/></div><div><label htmlFor="shipping_state">State</label><input id="shipping_state" type="text" name="shipping_state" value={formData.shipping_state} onChange={change} autoComplete="address-level1" required/></div><div><label htmlFor="shipping_postal_code">Postal code</label><input id="shipping_postal_code" type="text" name="shipping_postal_code" value={formData.shipping_postal_code} onChange={change} autoComplete="postal-code" required/></div><div><label htmlFor="shipping_country">Country</label><input id="shipping_country" type="text" name="shipping_country" value={formData.shipping_country} onChange={change} autoComplete="country-name" required/></div></div>
    <div className="ara-form-bottom"><div className="ara-form-note">The artist will review your order and get in touch if required. Payment options and the expected delivery date will be available once your order is accepted.</div><button type="submit" className="ara-submit" disabled={checkoutLoading}>{checkoutLoading?'Submitting…':'Submit Order Request'}</button><p className="ara-order-caption">No payment is requested at this stage.</p></div>
   </form></section>
  </>}
 </main>
}
function formatPrice(v){return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(v||0))}
