import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { apiUrl } from '../config/api'
import './OrderDetails.css'

const STATUS_LABELS={PENDING_ACCEPTANCE:'Pending Acceptance',ACCEPTED:'Accepted',PAYMENT_DUE:'Payment Due',PAID:'Paid',PROCESSING:'Processing',DISPATCHED:'Dispatched',DELIVERED:'Delivered',REJECTED:'Rejected',CANCELLED:'Cancelled'}
const money=value=>Number(value||0).toLocaleString('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2})
const formatDate=value=>value?new Date(String(value).replace(' ','T')).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):'—'
const journeyLabels={ORDERED:'Order placed',ACCEPTED:'Order accepted',PAYMENT_DUE:'Payment due',PAID:'Payment received',PROCESSING:'Artwork preparation',DISPATCHED:'Artwork dispatched',DELIVERED:'Artwork delivered',REJECTED:'Order rejected',CANCELLED:'Order cancelled'}

export default function OrderDetails(){
 const {id}=useParams();const navigate=useNavigate();const [order,setOrder]=useState(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [cancelling,setCancelling]=useState(false)
 useEffect(()=>{loadOrder()},[id])
 const loadOrder=async()=>{try{setLoading(true);setError('');const response=await fetch(apiUrl('orders/my-orders.php'),{credentials:'include',cache:'no-store'});const data=await response.json().catch(()=>({}));if(response.status===401){navigate('/login',{replace:true});return}if(!response.ok||!data.success)throw new Error(data.message||'Unable to load your orders.');const found=(data.orders||[]).find(item=>String(item.id)===String(id));if(!found)throw new Error('We could not find this order.');setOrder(found)}catch(err){setError(err.message||'Unable to load this order.')}finally{setLoading(false)}}
 const cancelOrder=async()=>{if(cancelling||!order)return;if(!window.confirm('Cancel this order? This cannot be undone.'))return;setCancelling(true);try{const response=await fetch(apiUrl('orders/cancel.php'),{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},credentials:'include',body:JSON.stringify({order_id:order.id})});const data=await response.json().catch(()=>({}));if(!response.ok||!data.success)throw new Error(data.message||'Unable to cancel this order.');await loadOrder()}catch(err){setError(err.message||'Unable to cancel this order.')}finally{setCancelling(false)}}
 if(loading)return <main className="ara-order-details"><div className="ara-order-page-state"><span className="ara-loader"/><p>Loading your order...</p></div></main>
 if(error||!order)return <main className="ara-order-details"><div className="ara-order-page-state"><span>◇</span><h1>Order unavailable</h1><p>{error||'We could not find this order.'}</p><button className="ara-btn ara-btn-primary" onClick={()=>navigate('/track-orders')}>Back to Orders</button></div></main>
 const items=Array.isArray(order.items)?order.items:[];const released=Boolean(order.price_released_at);const status=STATUS_LABELS[order.status]||order.status||'Unknown';const isPaid=order.status==='PAID'||Boolean(order.paid_at);const canCancel=['PENDING_ACCEPTANCE','ACCEPTED','PAYMENT_DUE','REJECTED'].includes(order.status)&&order.status!=='CANCELLED';
 const history=Array.isArray(order.history)?order.history:[];const journey=[{key:'ORDERED',label:'Order placed',date:order.created_at},{key:'ACCEPTED',label:'Order accepted',date:order.accepted_at},{key:'PAYMENT_DUE',label:'Payment due',date:order.status==='PAYMENT_DUE'?order.price_released_at:null},{key:'PAID',label:'Payment received',date:order.paid_at},{key:'PROCESSING',label:'Artwork preparation',date:order.status==='PROCESSING'?order.updated_at:null},{key:'DISPATCHED',label:'Artwork dispatched',date:order.dispatched_at},{key:'DELIVERED',label:'Artwork delivered',date:order.delivered_at}].filter(step=>step.date);history.forEach(entry=>{if(['REJECTED','CANCELLED'].includes(entry.new_status)&&!journey.some(step=>step.key===entry.new_status))journey.push({key:entry.new_status,label:journeyLabels[entry.new_status],date:entry.created_at})});
 return <main className="ara-order-details">
  <div className="ara-order-page-header"><div><Link to="/track-orders" className="ara-order-back">← Back to your orders</Link><span className="ara-orders-eyebrow">ORDER DETAILS</span><h1>#{order.order_number}</h1><p>Placed {formatDate(order.created_at)}</p></div><div className="ara-order-header-action">{canCancel&&<button type="button" className="ara-order-cancel-button" onClick={cancelOrder} disabled={cancelling}>{cancelling?'Cancelling…':'Cancel Order'}</button>}</div></div>
  <div className="ara-order-page-grid">
   <section className="ara-order-page-card"><span className="ara-orders-eyebrow">01 · ARTWORK</span><h2>Your artwork</h2>{items.map(item=><div className="ara-order-page-item" key={item.id}><div className="ara-order-page-item-placeholder">✦</div><div><strong>{item.painting_name}</strong><span>Quantity {item.quantity}</span></div><strong>{money(item.total_price)}</strong></div>)}</section>
   <section className="ara-order-page-card"><span className="ara-orders-eyebrow">02 · ORDER STATUS</span><h2>Where your order stands</h2><div className="ara-order-status-panel"><strong>{status}</strong><p>{order.status==='PENDING_ACCEPTANCE'?'Your order is with the artist for acceptance.':order.status==='ACCEPTED'?'Your order has been accepted. The final quotation will follow.':order.status==='PAYMENT_DUE'?'Your final quotation is ready and payment is due.':order.status==='PAID'?'Payment received. Your artwork is now moving through preparation.':order.status==='PROCESSING'?'Your artwork is being prepared.':order.status==='DISPATCHED'?'Your artwork has been dispatched.':order.status==='DELIVERED'?'Your artwork has been delivered.':order.status==='CANCELLED'?'This order was cancelled by you.':order.status==='REJECTED'?'The artist has rejected this order.':'Your order status has been updated.'}</p>{order.status==='PAYMENT_DUE'&&order.payment_link&&<a className="ara-btn ara-btn-primary ara-payment-link" href={order.payment_link} target="_blank" rel="noreferrer">Make Payment →</a>}</div></section>
   <section className="ara-order-page-card ara-order-page-price"><span className="ara-orders-eyebrow">03 · {released?'FINAL QUOTATION':'ORDER VALUE'}</span><div className="ara-order-card-heading-row"><h2>{released?'Your released quote':'Base price'}</h2>{released&&isPaid&&<button type="button" className="ara-invoice-button" disabled title="Invoice download will be available with the invoice module">Invoice</button>}</div>{released?<div className="ara-order-financial"><div><span>Base price</span><strong>{money(order.base_amount)}</strong></div><div><span>Customization fee</span><strong>{money(order.customization_amount)}</strong></div><div><span>Delivery fee</span><strong>{money(order.delivery_amount??order.shipping_amount)}</strong></div><div><span>Discount</span><strong>− {money(order.discount_amount)}</strong></div><div className="total"><span>Final amount</span><strong>{money(order.total_amount)}</strong></div></div>:<div className="ara-order-pending-price"><strong>{money(order.base_amount??order.subtotal)}</strong><p>The final quotation will be released after your order is accepted by the artist.</p></div>}</section>
   <section className="ara-order-page-card ara-order-journey-card"><span className="ara-orders-eyebrow">04 · ORDER JOURNEY</span><h2>Your order journey</h2><div className="ara-order-journey-scroll"><div className="ara-order-journey">{journey.slice().reverse().map((step,index)=><div className={`ara-order-journey-step ${index===0?'current':''}`} key={`${step.key}-${step.date}`}><span className="ara-order-journey-dot"/><div><strong>{step.label}</strong><small>{formatDate(step.date)}</small></div></div>)}</div></div></section>
   {(order.customer_notes||order.tracking_courier||order.tracking_id)&&<section className="ara-order-page-card"><span className="ara-orders-eyebrow">05 · DETAILS</span><h2>Order details</h2>{order.customer_notes&&<div className="ara-order-note"><span>YOUR NOTE</span><p>{order.customer_notes}</p></div>}{(order.tracking_courier||order.tracking_id)&&<div className="ara-order-shipment"><span>SHIPMENT</span><strong>{order.tracking_courier||'Courier'}{order.tracking_id?` · ${order.tracking_id}`:''}</strong>{order.tracking_url&&<a href={order.tracking_url} target="_blank" rel="noreferrer">Track shipment →</a>}</div>}</section>}
  </div>
 </main>
}
