import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { apiUrl } from '../config/api'
import { useToast } from '../components/ToastProvider'

const STATUS_LABELS={PENDING_ACCEPTANCE:'Pending Acceptance',ACCEPTED:'Accepted',PAYMENT_DUE:'Payment Due',PAID:'Paid',PROCESSING:'Processing',DISPATCHED:'Dispatched',DELIVERED:'Delivered',REJECTED:'Rejected',CANCELLED:'Cancelled'}
const getImageUrl=url=>!url?'':url.startsWith('http')?url:`http://localhost${url}`
const money=value=>Number(value||0).toLocaleString('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2})

export default function TrackOrders(){
 const {toast}=useToast();const [orders,setOrders]=useState([]);const [loading,setLoading]=useState(true);const [authenticated,setAuthenticated]=useState(false);const [error,setError]=useState('');const [selected,setSelected]=useState(null)
 useEffect(()=>{loadOrders(true);const interval=setInterval(()=>loadOrders(false),15000);return()=>clearInterval(interval)},[])
 const loadOrders=async(showLoading=false)=>{try{if(showLoading)setLoading(true);setError('');const response=await fetch(apiUrl('orders/my-orders.php'),{credentials:'include',cache:'no-store'});const data=await response.json().catch(()=>({}));if(response.status===401){setAuthenticated(false);return}if(!response.ok||!data.success)throw new Error(data.message||'Unable to load your orders.');setAuthenticated(true);setOrders(data.orders||[]);setSelected(current=>current?((data.orders||[]).find(order=>order.id===current.id)||current):null)}catch(err){if(showLoading)setError(err.message||'Unable to load your orders.')}finally{if(showLoading)setLoading(false)}}
 const openOrder=order=>setSelected(order)
 const closeOrder=()=>setSelected(null)
 if(loading)return <div className="ara-collection-state"><span className="ara-loader"></span><p>Loading your orders...</p></div>
 if(!authenticated&&!error)return <div className="ara-collection-state" style={{textAlign:'center'}}><strong>Sign in to track your orders</strong><p>Your orders are securely linked to your account. Sign in to view order status, quotation and payment details.</p><Link to="/login" className="ara-btn ara-btn-primary">Sign In</Link></div>
 if(error)return <div className="ara-collection-state ara-error-state"><strong>Unable to load your orders</strong><p>{error}</p><button type="button" onClick={()=>loadOrders(true)}>Try Again</button></div>
 return <section className="ara-orders"><div className="ara-orders-heading"><div><span className="ara-orders-eyebrow">YOUR JOURNEY</span><h2>Track Orders</h2></div><span className="ara-orders-count">{orders.length} {orders.length===1?'order':'orders'}</span></div>{orders.length===0?<div className="ara-collection-state"><strong>No orders yet</strong><p>Once you place an order, its status and delivery details will appear here.</p><Link to="/paintings" className="ara-btn ara-btn-primary">Explore Paintings</Link></div>:<div className="ara-order-list">{orders.map(order=>{const items=Array.isArray(order.items)?order.items:[];const preview=items.find(item=>item.image_url)?.image_url||'';const firstItem=items[0];const itemCount=items.reduce((total,item)=>total+Number(item.quantity||0),0);return <button type="button" className="ara-order-banner" key={order.id} onClick={()=>openOrder(order)}><div className="ara-order-art">{preview?<img src={getImageUrl(preview)} alt={firstItem?.painting_name||'Ordered painting'}/>:<div className="ara-order-art-placeholder"><span>ARAMANE ARTS</span><strong>Heritage</strong></div>}</div><div className="ara-order-main"><div className="ara-order-topline"><div><span className="ara-order-label">ORDER</span><h3>#{order.order_number}</h3></div><span className={`ara-order-status ara-status-${getStatusKey(order.status)}`}>{STATUS_LABELS[order.status]||order.status||'Unknown'}</span></div><div className="ara-order-content"><div className="ara-order-painting"><span className="ara-order-category">YOUR COLLECTION</span><strong>{firstItem?.painting_name||'Painting order'}</strong>{items.length>1&&<span className="ara-order-more">+ {items.length-1} more {items.length===2?'painting':'paintings'}</span>}</div><div className="ara-order-meta"><div><span>PLACED</span><strong>{new Date(order.created_at).toLocaleDateString()}</strong></div><div><span>ITEMS</span><strong>{itemCount||items.length||1}</strong></div><div><span>{order.price_released_at?'TOTAL':'BASE PRICE'}</span><strong>{money(order.total_amount)}</strong></div></div></div>{(order.tracking_courier||order.tracking_id)&&<div className="ara-order-tracking"><span className="ara-tracking-dot"/><div><span>SHIPMENT</span><strong>{order.tracking_courier||'Courier'}{order.tracking_id?` · ${order.tracking_id}`:''}</strong></div></div>}</div><span className="ara-order-arrow" aria-hidden="true">→</span></button>})}</div>}
 {selected&&<OrderModal order={selected} close={closeOrder} toast={toast}/>}</section>
}

function OrderModal({order,close,toast}){const released=Boolean(order.price_released_at);const items=order.items||[];return <div className="ara-order-modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)close()}}><div className="ara-order-modal" role="dialog" aria-modal="true" aria-label={`Order ${order.order_number}`}><button type="button" className="ara-order-modal-close" onClick={close} aria-label="Close order details">×</button><div className="ara-order-modal-header"><div><span className="ara-orders-eyebrow">ORDER DETAILS</span><h2>#{order.order_number}</h2><span className={`ara-order-status ara-status-${getStatusKey(order.status)}`}>{STATUS_LABELS[order.status]||order.status}</span></div><div className="ara-order-modal-art">{items[0]?.image_url&&<img src={getImageUrl(items[0].image_url)} alt={items[0].painting_name||'Painting'}/>}</div></div><div className="ara-order-modal-section"><span className="ara-orders-eyebrow">ARTWORK</span>{items.map(item=><div className="ara-modal-item" key={item.id}><strong>{item.painting_name}</strong><span>Quantity {item.quantity}</span><span>{money(item.total_price)}</span></div>)}</div><div className="ara-order-modal-section"><span className="ara-orders-eyebrow">PRICE</span>{released?<div className="ara-modal-financial"><div><span>Base price</span><strong>{money(order.base_amount)}</strong></div><div><span>Customization fee</span><strong>{money(order.customization_amount)}</strong></div><div><span>Delivery fee</span><strong>{money(order.delivery_amount??order.shipping_amount)}</strong></div><div><span>Discount</span><strong>− {money(order.discount_amount)}</strong></div><div className="ara-modal-total"><span>Final amount</span><strong>{money(order.total_amount)}</strong></div></div>:<div className="ara-modal-pending"><strong>Final quotation pending</strong><p>The artist will release the customization and delivery charges, discount and final amount after accepting your order.</p><span>Base price · {money(order.base_amount??order.subtotal)}</span></div>}</div>{released&&<div className="ara-order-modal-payment"><div><span className="ara-orders-eyebrow">PAYMENT</span><h3>Payment is {order.status==='PAID'?'complete':'due'}</h3><p>{order.payment_link?'Your payment link is ready.':'Your final price is released. The payment link has not been added yet.'}</p></div><button type="button" className="ara-payment-button" onClick={()=>{if(order.payment_link)window.open(order.payment_link,'_blank','noopener,noreferrer');else toast?.info?.('Payment link is yet to be released.')}}>{order.payment_link?'Make Payment':'Payment Link Pending'}</button></div>}<div className="ara-order-modal-footer"><span>Placed {new Date(order.created_at).toLocaleDateString('en-IN')}</span>{order.tracking_url&&<a href={order.tracking_url} target="_blank" rel="noreferrer">Track shipment →</a>}</div></div></div>}
function getStatusKey(status){return String(status||'unknown').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
