import { createPortal } from 'react-dom'
import { useEffect, useId, useRef, useState } from 'react'
import './UniversalDropdown.css'

export default function UniversalDropdown({ value, onChange, options = [], placeholder = 'Select an option', disabled = false, required = false, name, label, id, className = '' }) {
  const generatedId = useId(); const buttonId = id || `ara-admin-dropdown-${generatedId}`; const listboxId = `${buttonId}-listbox`; const rootRef = useRef(null); const menuRef = useRef(null); const [open, setOpen] = useState(false); const [activeIndex, setActiveIndex] = useState(0); const [menuStyle, setMenuStyle] = useState({top:0,left:0,width:0})
  const normalized = options.map(option => typeof option === 'string' ? { value: option, label: option } : { ...option, value: String(option.value), label: option.label ?? String(option.value) })
  const selectedIndex = normalized.findIndex(option => String(option.value) === String(value)); const selected = selectedIndex >= 0 ? normalized[selectedIndex] : null
  const positionMenu=()=>{const rect=rootRef.current?.querySelector('.ara-universal-dropdown-trigger')?.getBoundingClientRect();if(rect)setMenuStyle({top:rect.bottom+6,left:rect.left,width:rect.width})}
  useEffect(()=>{if(!open)return undefined;positionMenu();const close=event=>{if(!rootRef.current?.contains(event.target)&&!menuRef.current?.contains(event.target))setOpen(false)};const reposition=()=>positionMenu();document.addEventListener('pointerdown',close);window.addEventListener('resize',reposition);window.addEventListener('scroll',reposition,true);return()=>{document.removeEventListener('pointerdown',close);window.removeEventListener('resize',reposition);window.removeEventListener('scroll',reposition,true)}},[open])
  useEffect(()=>{if(selectedIndex>=0)setActiveIndex(selectedIndex)},[selectedIndex])
  const choose=option=>{if(disabled||option.disabled)return;onChange?.(option.value,option);setOpen(false)}
  const keyDown=event=>{if(disabled)return;if(event.key==='Escape'){if(open){event.preventDefault();setOpen(false)}return}if(event.key==='ArrowDown'||event.key==='ArrowUp'){event.preventDefault();if(!open){setOpen(true);setActiveIndex(selectedIndex>=0?selectedIndex:0);return}setActiveIndex(current=>normalized.length?(current+(event.key==='ArrowDown'?1:-1)+normalized.length)%normalized.length:0);return}if(event.key==='Home'||event.key==='End'){if(!open||!normalized.length)return;event.preventDefault();setActiveIndex(event.key==='Home'?0:normalized.length-1);return}if(event.key==='Enter'||event.key===' '){event.preventDefault();if(!open){setOpen(true);setActiveIndex(selectedIndex>=0?selectedIndex:0);return}if(normalized[activeIndex])choose(normalized[activeIndex])}}
  const menu=open?createPortal(<div ref={menuRef} id={listboxId} style={menuStyle} className="ara-universal-dropdown-menu" role="listbox" aria-labelledby={buttonId}>{normalized.length?normalized.map((option,index)=><button type="button" role="option" aria-selected={selectedIndex===index} disabled={option.disabled} className={`ara-universal-dropdown-option ${selectedIndex===index?'is-selected':''} ${activeIndex===index?'is-active':''}`} key={`${option.value}-${index}`} onMouseEnter={()=>setActiveIndex(index)} onClick={()=>choose(option)}><span>{option.label}</span>{selectedIndex===index&&<span className="ara-universal-dropdown-check">✓</span>}</button>):<div className="ara-universal-dropdown-empty">No options available</div>}</div>,document.body):null
  return <><div className={`ara-universal-dropdown ${className}`.trim()} ref={rootRef}>{label&&<span className="ara-universal-dropdown-label">{label}</span>}{name&&<input type="hidden" name={name} value={value??''} required={required}/>}<button id={buttonId} type="button" className={`ara-universal-dropdown-trigger ${open?'is-open':''}`} aria-haspopup="listbox" aria-expanded={open} aria-controls={listboxId} disabled={disabled} onClick={()=>setOpen(current=>!current)} onKeyDown={keyDown}><span className={selected?'':'is-placeholder'}>{selected?.label||placeholder}</span><span className="ara-universal-dropdown-chevron" aria-hidden="true">⌄</span></button></div>{menu}</>
}
