import { useEffect, useState } from 'react'
import { BrowserRouter, Routes, Route, useLocation, useNavigationType } from 'react-router-dom'
import Home from './pages/Home'
import Paintings from './pages/Paintings'
import PaintingDetails from './pages/PaintingDetails'
import Login from './pages/Login'
import ResetPassword from './pages/ResetPassword'
import Account from './pages/Account'
import Cart from './pages/Cart'
import TrackOrders from './pages/TrackOrders'
import OrderDetails from './pages/OrderDetails'
import PrivacyPolicy from './pages/PrivacyPolicy'
import TermsAndConditions from './pages/TermsAndConditions'
import FAQ from './pages/FAQ'
import Layout from './components/Layout'
import { ToastProvider } from './components/ToastProvider'
import { apiUrl } from './config/api'
const SITE_NAME='ARAmane Arts',DEFAULT_DESCRIPTION='Original Thanjavur paintings handcrafted with devotion and heritage.',COLLECTION_SCROLL_KEY='ara-collection-scroll'
function setMeta(n,c){let e=document.head.querySelector(`meta[name="${n}"]`);if(!e){e=document.createElement('meta');e.setAttribute('name',n);document.head.appendChild(e)}e.setAttribute('content',c)}function setProperty(n,c){let e=document.head.querySelector(`meta[property="${n}"]`);if(!e){e=document.createElement('meta');e.setAttribute('property',n);document.head.appendChild(e)}e.setAttribute('content',c)}function setCanonical(u){let e=document.head.querySelector('link[rel="canonical"]');if(!e){e=document.createElement('link');e.rel='canonical';document.head.appendChild(e)}e.href=u}function getImageUrl(u){if(!u)return'';if(u.startsWith('http'))return u;return`${window.location.origin}${u}`}
function MetadataManager(){const l=useLocation();useEffect(()=>{let cancelled=false;const origin=window.location.origin,canonical=`${origin}${l.pathname}${l.search}`;document.title=l.pathname==='/'?SITE_NAME:`${SITE_NAME} — ${l.pathname.startsWith('/paintings')?'Collection':l.pathname==='/faq'?'FAQs':'Account'}`;setMeta('description',DEFAULT_DESCRIPTION);setProperty('og:site_name',SITE_NAME);setProperty('og:type','website');setProperty('og:title',document.title);setProperty('og:description',DEFAULT_DESCRIPTION);setProperty('og:url',canonical);setMeta('twitter:card','summary_large_image');setMeta('twitter:title',document.title);setMeta('twitter:description',DEFAULT_DESCRIPTION);setCanonical(canonical);const m=l.pathname.match(/^\/paintings\/([^/]+)$/);if(m)(async()=>{try{const r=await fetch(apiUrl(`paintings/get.php?id=${encodeURIComponent(m[1])}`)),d=await r.json().catch(()=>({})),p=d.painting||d.data;if(cancelled||!r.ok||!d.success||!p)return;const title=p.name?`${p.name} | ${SITE_NAME}`:SITE_NAME,desc=p.description||`Discover ${p.name||'this original Thanjavur painting'} from ${SITE_NAME}.`,image=getImageUrl(p.images?.[0]?.image_url||p.image_url);document.title=title;setMeta('description',desc);setProperty('og:type','product');setProperty('og:title',title);setProperty('og:description',desc);setProperty('og:url',canonical);if(image){setProperty('og:image',image);setMeta('twitter:image',image)}}catch{}})();return()=>{cancelled=true}},[l.pathname,l.search]);return null}
function ScrollManager(){const l=useLocation(),n=useNavigationType();useEffect(()=>{const is=l.pathname==='/paintings',saved=sessionStorage.getItem(COLLECTION_SCROLL_KEY);if(is&&n==='POP'&&saved!==null){const y=Number(saved);sessionStorage.removeItem(COLLECTION_SCROLL_KEY);requestAnimationFrame(()=>requestAnimationFrame(()=>window.scrollTo(0,Number.isFinite(y)?y:0)));return}window.scrollTo({top:0,left:0,behavior:'auto'})},[l.pathname,n]);useEffect(()=>{if(l.pathname!=='/paintings')return;return()=>sessionStorage.setItem(COLLECTION_SCROLL_KEY,String(window.scrollY||0))},[l.pathname]);return null}
function MaintenanceGate(){const[maintenance,setMaintenance]=useState(null),[retryTick,setRetryTick]=useState(0);useEffect(()=>{let active=true;const check=async()=>{try{const r=await fetch(apiUrl('system/maintenance.php'),{headers:{Accept:'application/json'},cache:'no-store'}),d=await r.json().catch(()=>({}));if(active&&r.ok&&d.success===true)setMaintenance(d.maintenance_mode===true)}catch{}};check();const t=setInterval(check,2000);return()=>{active=false;clearInterval(t)}},[retryTick]);if(maintenance===null)return <div className="ara-maintenance-loading"/>;if(!maintenance)return null;return <div className="ara-maintenance-screen" role="alertdialog" aria-modal="true"><div className="ara-maintenance-inner"><span className="ara-maintenance-eyebrow">ARAmane Arts</span><div className="ara-maintenance-mark">A</div><h1>We are preparing something beautiful.</h1><div className="ara-maintenance-rule"/><p>Our website is temporarily unavailable while we carry out scheduled work. We will be back shortly.</p><span className="ara-maintenance-note">Thank you for your patience.</span><button type="button" className="ara-maintenance-retry" onClick={()=>setRetryTick(v=>v+1)}>Check again</button></div><style>{`.ara-maintenance-screen{position:fixed;inset:0;z-index:2147483647;background:#faf6ee;color:#5b1217;display:flex;align-items:center;justify-content:center;min-height:100dvh;width:100vw;text-align:center;padding:24px;box-sizing:border-box}.ara-maintenance-inner{width:min(620px,100%);display:flex;flex-direction:column;align-items:center}.ara-maintenance-eyebrow{font:600 10px/1.2 'DM Sans',sans-serif;letter-spacing:.32em;color:#b18d2d}.ara-maintenance-mark{width:72px;height:72px;margin:28px 0 24px;border:1px solid rgba(91,18,23,.2);border-radius:50%;display:grid;place-items:center;font:400 42px/1 'Cormorant Garamond',serif}.ara-maintenance-inner h1{margin:0;font:400 clamp(38px,7vw,68px)/.95 'Cormorant Garamond',serif}.ara-maintenance-rule{width:74px;height:1px;background:#d4af37;margin:28px 0}.ara-maintenance-inner p{max-width:490px;font:400 15px/1.8 'DM Sans',sans-serif;color:#6e5b53}.ara-maintenance-retry{margin-top:28px;padding:11px 18px;background:transparent;border:1px solid #5b1217}.ara-maintenance-loading{display:none}`}</style></div>}
export default function App(){return <BrowserRouter><MaintenanceGate/><MetadataManager/><ScrollManager/><ToastProvider><Layout><Routes><Route path="/" element={<Home/>}/><Route path="/paintings" element={<Paintings/>}/><Route path="/paintings/:id" element={<PaintingDetails/>}/><Route path="/faq" element={<FAQ/>}/><Route path="/login" element={<Login/>}/><Route path="/reset-password" element={<ResetPassword/>}/><Route path="/account" element={<Account/>}/><Route path="/cart" element={<Cart/>}/><Route path="/track-orders" element={<TrackOrders/>}/><Route path="/track-orders/:id" element={<OrderDetails/>}/><Route path="/privacy-policy" element={<PrivacyPolicy/>}/><Route path="/terms-and-conditions" element={<TermsAndConditions/>}/></Routes></Layout></ToastProvider></BrowserRouter>}
